// Copyright (C) 2015-2018 IllFonic, LLC. and Gun Media

#pragma once

#include "Projectiles/SCProjectile.h"
#include "SCFlare_Projectile.generated.h"

class USCBaseDamageType;
class USCScoringEvent;

/**
 * @class ASCFalre_Projectile
 */
UCLASS()
class SUMMERCAMP_API ASCFlare_Projectile : public ASCProjectile
{
	GENERATED_BODY()
	
public:
	ASCFlare_Projectile(const FObjectInitializer& ObjectInitializer);
	
	// Begin AActor interface
	virtual void PostInitializeComponents() override;
	virtual void Destroyed() override;
	virtual void Tick(float DeltaSeconds) override;
	// End AActor interface

	/** If the flare bounces off an object see if it was the killer. */
	UFUNCTION()
	void OnFlareBounce(const FHitResult& ImpactResult, const FVector& ImpactVelocity);

	/** If the flare stops on an object see if it was the killer. */
	UFUNCTION()
	void OnFlareStop(const FHitResult& HitResult);

protected:

	// The light generated by the flare
	UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
	USpotLightComponent* FlareSpotLight;

	UPROPERTY(VisibleDefaultsOnly, BlueprintReadOnly)
	UParticleSystemComponent* KillerEyeFlareParticles;

	// The amount of damage if the flare doesn't get stuck in the killer's eye
	UPROPERTY(EditDefaultsOnly)
	float FlareLightDamage;

	// The amount of damage if the flare gets stuck in the killer's eye
	UPROPERTY(EditDefaultsOnly)
	float FlareHeavyDamage;

	// If the killer is within this radius of the flare he will sow on counselor minimaps
	UPROPERTY(EditDefaultsOnly)
	float KillerMinDistance;

	// The damage type if the flare doesn't get stuck in the killer's eye
	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<USCBaseDamageType> FlareLightDamageType;

	// The damage type if the flare gets stuck in the killer's eye
	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<USCBaseDamageType> FlareHeavyDamageType;

	// Score event for spotting the killer with a flare
	UPROPERTY(EditDefaultsOnly, Category = "Scoring")
	TSubclassOf<USCScoringEvent> FlareScoreEventClass;

	// Score event for stunning the killer with a flare
	UPROPERTY(EditDefaultsOnly, Category = "Scoring")
	TSubclassOf<USCScoringEvent> FlareStunScoreEventClass;

	UPROPERTY(ReplicatedUsing=OnRep_AttachedToKiller)
	bool bAttachedToKiller;

	UFUNCTION()
	void OnRep_AttachedToKiller();
};
